name: Compliance License Check

on: [pull_request]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check Licenses
        run: npx license-checker --summary
